### ISSUE TITLE
Feature List Improvements

### ISSUE THREAD

**Issue by idbentley** [DaedalusG/NoiseWave#1]
Hello SoundCloud Team!

After reviewing your feature list documentation, here is a list of our feedback. Please address these concerns today (Thursday July 9) and send a message in your slack channel when addressed.

 - Use markdown to improve readability of feature list
 - Specify if features are strictly API functionality or user facing.
 - Expand bullet points to full sentences, and specify details
     - e.x. "Create: load new songs" - "Create: Form for uploading songs, and specifying attributes.  Server side transfer uploaded songs to s3 for long term storage."
  - "READ" is not really "play songs" it is the information page relating to a given song.  Playing a song is a AJAX streaming operation directly from S3, rather than a RESTful endpoint on your server.
 - On destroy, do you delete from s3?
 - In order to implement continuous play, the site must be a "Single Page App" - It may be easier if you identify, which portions of the site will interrupt play (like song upload, for example). [TALK TO YOUR TA BEFORE TACKLING THIS]
 - Expand on User administration  (signup, login, logout, profile, etc..)
 - Both comments and likes should support all four CRUD operations.
 - Clarify distinction between database and table in features - I.e. "user database" vs. "song database" are these different databases or just different tables?
 - Feature list should not specify database concerns, instead should list what functionality is provided.  "As a user I want to be able to comment on a song at a particular timestamp.  My comment should display when a listening user reaches that timestamp"
 - Add feature supporting audio waveform visualization - here's an example using vanilla JS (https://css-tricks.com/making-an-audio-waveform-visualizer-with-vanilla-javascript/)
 - Second line under User Pages seems like a duplicate of Song CRUD operations above.
 - Add Heroku hosting of site and database as feature
 - Add high quality README.md and documentation as feature
 - Your bonus' are great, let's make waveform visualization a required feature, and please expand upon each of the other bonus'

**Comment by DaedalusG** [comment]
Improvements made
